#!/bin/bash

# Скрипт для помощи в настройке GitHub Secrets
# Показывает что нужно добавить в GitHub Secrets

echo "🔐 Настройка GitHub Secrets для автоматического деплоя"
echo "======================================================"
echo ""
echo "Перейдите в настройки репозитория:"
echo "https://github.com/aoneagency001-maker/lead-generation-system/settings/secrets/actions"
echo ""
echo "Добавьте следующие Secrets:"
echo ""
echo "1️⃣ VPS_HOST"
echo "   Значение: ваш IP или домен VPS"
echo "   Пример: 123.45.67.89 или vps.example.com"
echo ""
echo "2️⃣ VPS_USER"
echo "   Значение: пользователь для SSH"
echo "   Пример: root или deploy"
echo ""
echo "3️⃣ VPS_SSH_KEY"
echo "   Значение: приватный SSH ключ"
echo ""
echo "   Для генерации ключа выполните:"
echo "   ssh-keygen -t ed25519 -C 'github-actions-deploy' -f ~/.ssh/github_actions_deploy"
echo ""
echo "   Затем скопируйте содержимое:"
echo "   cat ~/.ssh/github_actions_deploy"
echo ""
echo "   И добавьте ВСЁ (включая BEGIN/END строки) в VPS_SSH_KEY"
echo ""
echo "4️⃣ VPS_DEPLOY_PATH (опционально)"
echo "   Значение: путь для деплоя на VPS"
echo "   По умолчанию: /opt/lead-generation-system"
echo ""
echo "📝 После добавления Secrets:"
echo "   1. Скопируйте публичный ключ на VPS:"
echo "      ssh-copy-id -i ~/.ssh/github_actions_deploy.pub root@your-vps-ip"
echo ""
echo "   2. Проверьте подключение:"
echo "      ssh -i ~/.ssh/github_actions_deploy root@your-vps-ip"
echo ""
echo "   3. Запустите первый деплой вручную или дождитесь автоматического"
echo ""

